import { ALL_CUISINE_TYPES, FILTER_KEY_TO_DB_COLUMN } from "@/lib/amenities";

export const CUISINE_KEYWORDS = [
  "italian",
  "chinese",
  "japanese",
  "indian",
  "mexican",
  "thai",
  "french",
  "american",
  "british",
  "mediterranean",
  "spanish",
  "vietnamese",
  "korean",
  "greek",
  "turkish",
  "lebanese",
  "brazilian",
  "caribbean",
  "moroccan",
  "european",
  "asian",
  "african",
]
  .concat(ALL_CUISINE_TYPES)
  .map((c) => c.toLowerCase());

export const FOOD_KEYWORDS = [
  "pizza",
  "burger",
  "sushi",
  "ramen",
  "curry",
  "tapas",
  "bbq",
  "seafood",
  "steak",
  "pasta",
  "noodles",
  "sandwich",
  "salad",
  "soup",
  "wings",
  "tacos",
  "burrito",
  "wrap",
  "kebab",
  "falafel",
  "shawarma",
  "dumplings",
  "dim sum",
  "pho",
  "pad thai",
  "fried rice",
  "chow mein",
  "biryani",
  "tikka",
  "masala",
];

export const FEATURE_KEYWORDS: Record<string, string[]> = {
  kidsMenu: [
    "kids menu",
    "children menu",
    "kids meal",
    "children's menu",
    "kid friendly menu",
  ],
  highChairs: [
    "high chair",
    "highchair",
    "baby chair",
    "high chairs",
    "baby chairs",
    "babychair",
    "highchairs",
    "babychairs",
  ],
  changingTable: [
    "changing table",
    "baby changing",
    "changing station",
    "diaper changing",
  ],
  wheelchairAccess: [
    "wheelchair",
    "accessible",
    "disability access",
    "wheelchair accessible",
  ],
  outdoorSeating: [
    "outdoor",
    "outside",
    "patio",
    "terrace",
    "garden",
    "alfresco",
  ],
  vegetarianOptions: ["vegetarian", "veggie options", "veggie"],
  veganOptions: ["vegan", "plant based", "plant-based"],
  glutenFree: ["gluten free", "gluten-free", "celiac"],
  halal: ["halal"],
  kosher: ["kosher"],
  parking: ["parking", "car park"],
  playgroundNearby: ["playground", "play area", "playground nearby"],
  dogFriendly: [
    "dog friendly",
    "pet friendly",
    "puppy friendly",
    "dogs allowed",
    "pets allowed",
    "puppies allowed",
    "dog",
    "puppy",
    "pet",
  ],
  takeaway: ["takeaway", "takeout", "to go", "delivery"],
  quickService: ["quick service", "fast service", "fast food"],
  goodForGroups: [
    "groups",
    "large groups",
    "parties",
    "family groups",
    "good for groups",
  ],
  freeKidsMeal: [
    "free kids meal",
    "kids eat free",
    "free children meal",
    "kid eats free",
  ],
  airConditioning: ["air conditioning", "air con", "ac", "climate control"],
  kidsPlaySpace: ["kids play space", "play space", "play room", "kids area"],
  kidsColoring: ["coloring", "colouring", "crayons", "coloring activities"],
  gamesAvailable: ["games", "board games", "activities"],
  healthyOptions: ["healthy", "healthy options", "nutritious"],
  smallPlates: ["small plates", "tapas", "sharing plates"],
  buzzy: ["buzzy", "lively", "energetic", "vibrant"],
  relaxed: ["relaxed", "casual", "laid back", "laid-back", "chill"],
  posh: ["posh", "upscale", "fancy", "fine dining", "elegant", "sophisticated"],
  funQuirky: ["quirky", "fun", "unique", "unusual", "different"],
  babyChangeWomens: [
    "baby change women",
    "changing room women",
    "ladies baby change",
  ],
  babyChangeMens: ["baby change men", "changing room men", "mens baby change"],
  babyChangeUnisex: ["baby change", "unisex baby change", "family bathroom"],
  pramStorage: ["pram storage", "stroller storage", "buggy storage"],
};

export const PRICE_KEYWORDS = {
  1: ["cheap", "budget", "inexpensive", "affordable", "$"],
  2: ["moderate", "mid-range", "reasonable", "$$"],
  3: ["expensive", "upscale", "fine dining", "$$$"],
  4: ["luxury", "high-end", "premium", "$$$$"],
};

export const RATING_KEYWORDS = [
  { pattern: /highly rated|top rated|best|excellent/i, rating: 4.5 },
  { pattern: /good rating|well rated/i, rating: 4.0 },
  { pattern: /(\d+\.?\d*)\s*(?:star|stars|\+)/i, extract: true },
];

export const STOP_WORDS = new Set([
  "and",
  "with",
  "the",
  "in",
  "at",
  "near",
  "a",
  "an",
  "for",
  "that",
  "has",
  "have",
  "is",
  "or",
  "to",
  "of",
  "some",
  "any",
]);

export const COMMON_CITIES = [
  // UK
  "london",
  "manchester",
  "birmingham",
  "leeds",
  "glasgow",
  "edinburgh",
  "liverpool",
  "bristol",
  "maidenhead",
  "cambridge",
  "oxford",
  "brighton",
  "southampton",
  "york",
  "nottingham",
  "sheffield",
  "leicester",
  "reading",
  "cardiff",
  // US
  "chicago",
  "san francisco",
  "sanfrancisco",
  "new york",
  "newyork",
  "los angeles",
  "losangeles",
  "houston",
  "phoenix",
  "philadelphia",
  "san antonio",
  "san diego",
  "dallas",
  "austin",
  "seattle",
  "boston",
  "denver",
  "portland",
  "miami",
  "atlanta",
  "detroit",
  "minneapolis",
  "tampa",
  "orlando",
  "cleveland",
  "pittsburgh",
  "sacramento",
  "las vegas",
  "lasvegas",
];
