import { ALL_CUISINE_TYPES } from "@/lib/db-amenities";

export const CUISINE_KEYWORDS = [
  "african",
  "american",
  "asian",
  "brazilian",
  "british",
  "caribbean",
  "chinese",
  "european",
  "french",
  "greek",
  "indian",
  "italian",
  "japanese",
  "korean",
  "lebanese",
  "mediterranean",
  "mexican",
  "moroccan",
  "spanish",
  "thai",
  "turkish",
  "vietnamese",
]
  .concat(ALL_CUISINE_TYPES)
  .map((c) => c.toLowerCase());

export const FOOD_KEYWORDS = [
  "bbq",
  "biryani",
  "burger",
  "burrito",
  "chow mein",
  "curry",
  "dim sum",
  "dumplings",
  "falafel",
  "fried rice",
  "hummus",
  "ice cream",
  "kebab",
  "masala",
  "noodles",
  "pad thai",
  "pasta",
  "pho",
  "pizza",
  "ramen",
  "salad",
  "sandwich",
  "seafood",
  "shawarma",
  "soup",
  "steak",
  "sushi",
  "tacos",
  "tapas",
  "tikka",
  "wings",
  "wrap",
];

export const FEATURE_KEYWORDS: Record<string, string[]> = {
  airConditioning: ["air conditioning", "air con", "climate control"],
  babyChangeMens: ["baby change men", "changing room men", "mens baby change"],
  babyChangeUnisex: [
    "baby change",
    "unisex baby change",
    "family bathroom",
    "baby changing",
  ],
  babyChangeWomens: [
    "baby change women",
    "changing room women",
    "ladies baby change",
  ],
  buzzy: ["buzzy", "lively", "energetic", "vibrant"],
  // changingTable: [
  //   "changing table",
  //   "baby changing",
  //   "changing station",
  //   "diaper changing",
  //   "diaper station",
  //   "diaper table",
  // ],
  dogFriendly: [
    "dog friendly",
    "pet friendly",
    "puppy friendly",
    "dogs allowed",
    "pets allowed",
    "puppies allowed",
    "dog",
    "puppy",
    "pet",
  ],
  freeKidsMeal: [
    "free kids meal",
    "kids eat free",
    "free children meal",
    "kid eats free",
  ],
  friendlyStaff: [
    "friendly staff",
    "great staff",
    "nice staff",
    "welcoming staff",
  ],
  funQuirky: ["quirky", "fun", "unique", "unusual", "different"],
  gamesAvailable: ["games", "board games", "activities"],
  glutenFreeOptions: [
    "gluten free options",
    "gluten-free options",
    "gluten free",
    "gluten-free",
    "celiac",
  ],
  goodForGroups: [
    "groups",
    "large groups",
    "parties",
    "family groups",
    "good for groups",
  ],
  halal: ["halal"],
  healthyOptions: ["healthy", "healthy options", "nutritious"],
  highChairs: [
    "high chair",
    "highchair",
    "baby chair",
    "high chairs",
    "baby chairs",
    "babychair",
    "highchairs",
    "babychairs",
  ],
  kidsColoring: ["coloring", "colouring", "crayons", "coloring activities"],
  kidsMenu: [
    "kids menu",
    "children menu",
    "kids meal",
    "children's menu",
    "kid friendly menu",
    "kid's menu",
    "child menu",
    "child's menu",
  ],
  kidsPlaySpace: [
    "kids play space",
    "play space",
    "play room",
    "kids area",
    "play area",
    "playspace",
  ],
  kidsPottyToilet: [
    "potty",
    "kids toilet",
    "potty training",
    "kids potty",
    "toddler toilet",
  ],
  kosher: ["kosher"],
  onePoundKidsMeal: [
    "one pound kids meal",
    "£1 kids meal",
    "1 pound kids meal",
    "kids meal for a pound",
  ],
  outdoorSeating: [
    "outdoor",
    "outside",
    "patio",
    "terrace",
    "garden",
    "alfresco",
  ],
  playgroundNearby: ["playground", "playground nearby"],
  posh: ["posh", "upscale", "fancy", "fine dining", "elegant", "sophisticated"],
  pramStorage: ["pram storage", "stroller storage", "buggy storage"],
  quickService: ["quick service", "fast service", "fast food"],
  relaxed: ["relaxed", "casual", "laid back", "laid-back", "chill"],
  smallPlates: ["small plates", "tapas", "sharing plates"],
  takeaway: ["takeaway", "takeout", "to go", "delivery"],
  teenFavourite: [
    "teen",
    "teenager",
    "teens",
    "teen friendly",
    "good for teens",
  ],
  touristAttractionNearby: [
    "tourist attraction",
    "sightseeing",
    "near attraction",
    "tourist area",
  ],
  veganOptions: ["vegan", "plant based", "plant-based"],
  vegetarianOptions: ["vegetarian", "veggie options", "veggie"],
  wheelchairAccess: [
    "wheelchair",
    "accessible",
    "disability access",
    "wheelchair accessible",
  ],
};

export const PRICE_KEYWORDS = {
  1: ["cheap", "budget", "inexpensive", "affordable", "$"],
  2: ["moderate", "mid-range", "reasonable", "$$"],
  3: ["expensive", "upscale", "fine dining", "$$$"],
  4: ["luxury", "high-end", "premium", "$$$$"],
};

export const RATING_KEYWORDS = [
  { pattern: /highly rated|top rated|best|excellent/i, rating: 4.5 },
  { pattern: /good rating|well rated/i, rating: 4.0 },
  { pattern: /(\d+\.?\d*)\s*(?:star|stars|\+)/i, extract: true },
];

export const STOP_WORDS = new Set([
  "and",
  "with",
  "the",
  "in",
  "at",
  "near",
  "a",
  "an",
  "for",
  "that",
  "has",
  "have",
  "is",
  "or",
  "to",
  "of",
  "some",
  "any",
]);

export const VENUE_WORDS = new Set([
  "bar",
  "cafe",
  "eatery",
  "house",
  "joint",
  "kitchen",
  "place",
  "restaurant",
  "room",
  "shop",
  "spot",
]);

// ***Duplicates cities are intended for slug matching
export const COMMON_CITIES = [
  // UK
  "birmingham",
  "brighton",
  "bristol",
  "cambridge",
  "cardiff",
  "edinburgh",
  "glasgow",
  "guildford",
  "leeds",
  "leicester",
  "liverpool",
  "london",
  "maidenhead",
  "manchester",
  "nottingham",
  "oxford",
  "reading",
  "rye",
  "sheffield",
  "southampton",
  "york",
  // US
  "atlanta",
  "austin",
  "boston",
  "chicago",
  "cleveland",
  "dallas",
  "denver",
  "detroit",
  "houston",
  "las vegas",
  "lasvegas",
  "los angeles",
  "losangeles",
  "miami",
  "milwaukee",
  "minneapolis",
  "new york",
  "newyork",
  "orlando",
  "philadelphia",
  "phoenix",
  "pittsburgh",
  "portland",
  "sacramento",
  "san antonio",
  "san diego",
  "san francisco",
  "sanfrancisco",
  "seattle",
  "tampa",
  // Spain
  "valencia",
];
