import { ALL_CUISINE_TYPES } from "@/lib/db-amenities";

export const CUISINE_KEYWORDS = [
  "african",
  "american",
  "asian",
  "brazilian",
  "british",
  "caribbean",
  "chinese",
  "european",
  "french",
  "greek",
  "indian",
  "italian",
  "japanese",
  "korean",
  "lebanese",
  "mediterranean",
  "mexican",
  "moroccan",
  "spanish",
  "thai",
  "turkish",
  "vietnamese",
]
  .concat(ALL_CUISINE_TYPES)
  .map((c) => c.toLowerCase());

export const FOOD_KEYWORDS = [
  "bbq",
  "biryani",
  "burger",
  "burrito",
  "chow mein",
  "curry",
  "dim sum",
  "dumplings",
  "falafel",
  "fried rice",
  "hummus",
  "ice cream",
  "kebab",
  "masala",
  "noodles",
  "pad thai",
  "pasta",
  "pho",
  "pizza",
  "ramen",
  "salad",
  "sandwich",
  "seafood",
  "shawarma",
  "soup",
  "steak",
  "sushi",
  "tacos",
  "tapas",
  "tikka",
  "wings",
  "wrap",
];

export const FEATURE_KEYWORDS: Record<string, string[]> = {
  airConditioning: ["ac", "air conditioning", "air con", "climate control"],
  babyChangeMens: [
    "baby change men",
    "baby change mens",
    "mens baby change",
    "changing room men",
  ],
  babyChangeWomens: [
    "baby change women",
    "baby change womens",
    "ladies baby change",
    "changing room women",
  ],
  babyChangeUnisex: [
    "unisex baby change",
    "family bathroom",
    "baby change",
    "baby changing",
    "changing room",
  ],
  buzzy: ["buzzy", "lively", "energetic", "vibrant"],
  // changingTable: [
  //   "changing table",
  //   "baby changing",
  //   "changing station",
  //   "diaper changing",
  //   "diaper station",
  //   "diaper table",
  // ],
  dogFriendly: [
    "dog friendly",
    "dogs allowed",
    "dog allowed",
    "dogs welcome",
    "pet friendly",
    "pets allowed",
    "pet allowed",
    "pets welcome",
  ],
  freeKidsMeal: [
    "free kids meal",
    "kids eat free",
    "free children meal",
    "kid eats free",
    "kids free",
    "children eat free",
  ],
  friendlyStaff: [
    "friendly staff",
    "great staff",
    "nice staff",
    "welcoming staff",
    "good staff",
  ],
  funQuirky: ["quirky", "fun", "unique", "different"],
  gamesAvailable: ["games", "activities", "kids activities", "games available"],
  glutenFreeOptions: [
    "gluten free options",
    "gluten-free options",
    "gluten free",
    "gluten-free",
    "celiac",
  ],
  goodForGroups: [
    "groups",
    "large groups",
    "parties",
    "large parties",
    "family groups",
    "good for groups",
    "group booking",
  ],
  halal: ["halal", "halal options"],
  healthyOptions: ["healthy", "healthy options", "nutritious"],
  highChairs: [
    "high chair",
    "high chairs",
    "highchair",
    "highchairs",
    "baby chair",
    "baby chairs",
    "babychair",
    "babychairs",
  ],
  kidsColoring: [
    "coloring",
    "colouring",
    "kids coloring",
    "kids colouring",
    "crayons",
    "drawing",
  ],
  kidsMenu: [
    "kids menu",
    "kids meal",
    "kid's menu",
    "kid friendly menu",
    "child menu",
    "childs menu",
    "child's menu",
    "childrens menu",
    "children's menu",
  ],
  kidsPlaySpace: [
    "kids play space",
    "play space",
    "play room",
    "kids area",
    "play area",
    "playspace",
    "indoor play",
    "indoor play area",
    "indoor play space",
  ],
  kidsPottyToilet: [
    "potty",
    "kids toilet",
    "potty training",
    "kids potty",
    "toddler toilet",
  ],
  kosher: ["kosher", "kosher options"],
  onePoundKidsMeal: [
    "one pound kids meal",
    "£1 kids meal",
    "1 pound kids meal",
    "kids meal for a pound",
  ],
  outdoorSeating: [
    "outdoor",
    "outside",
    "patio",
    "terrace",
    "garden",
    "alfresco",
  ],
  playgroundNearby: ["playground", "playground nearby", "near playground"],
  posh: ["posh", "upscale", "fancy", "fine dining", "elegant", "sophisticated"],
  pramStorage: [
    "pram storage",
    "stroller storage",
    "buggy storage",
    "pram",
    "prams",
    "stroller",
    "strollers",
    "buggy",
    "buggies",
    "pushchair",
    "pushchairs",
  ],
  quickService: [
    "quick service",
    "fast service",
    "fast food",
    "counter service",
  ],
  relaxed: [
    "relaxed",
    "casual",
    "laid back",
    "laid-back",
    "chill",
    "cosy",
    "cozy",
    "comfortable",
  ],
  smallPlates: ["small plates", "tapas", "sharing plates"],
  takeaway: ["takeaway", "takeout", "to go", "delivery", "to-go"],
  teenFavourite: [
    "teen",
    "teens",
    "teenager",
    "teenagers",
    "teen friendly",
    "good for teens",
  ],
  touristAttractionNearby: [
    "tourist attraction",
    "near tourist attraction",
    "sightseeing",
    "near attraction",
    "tourist area",
    "near tourist area",
    "touristy",
  ],
  veganOptions: ["vegan", "vegan options", "plant based", "plant-based"],
  vegetarianOptions: [
    "vegetarian",
    "veggie options",
    "veggie",
    "vegetarian options",
    "meat free",
    "no meat",
  ],
  wheelchairAccess: [
    "wheelchair",
    "wheelchairs",
    "accessible",
    "accessibility",
    "disability access",
    "wheelchair access",
    "wheelchair accessible",
    "wheelchair accessibility",
  ],
};

export const PRICE_KEYWORDS = {
  1: ["cheap", "budget", "inexpensive", "affordable", "$"],
  2: ["moderate", "mid-range", "reasonable", "$$"],
  3: ["expensive", "upscale", "fine dining", "$$$"],
  4: ["luxury", "high-end", "premium", "$$$$"],
};

export const RATING_KEYWORDS = [
  { pattern: /highly rated|top rated|best|excellent/i, rating: 4.5 },
  { pattern: /good rating|well rated/i, rating: 4.0 },
  { pattern: /(\d+\.?\d*)\s*(?:star|stars|\+)/i, extract: true },
];

export const STOP_WORDS = new Set([
  "and",
  "with",
  "the",
  "in",
  "at",
  "near",
  "a",
  "an",
  "for",
  "that",
  "has",
  "have",
  "is",
  "or",
  "to",
  "of",
  "some",
  "any",
]);

export const VENUE_WORDS = new Set([
  "bar",
  "cafe",
  "eatery",
  "house",
  "joint",
  "kitchen",
  "place",
  "restaurant",
  "shop",
  "spot",
]);

// ***Duplicates cities for slug matching
export const COMMON_CITIES = [
  // UK cities
  "birmingham",
  "brighton",
  "bristol",
  "cambridge",
  "cardiff",
  "edinburgh",
  "glasgow",
  "guildford",
  "leeds",
  "leicester",
  "liverpool",
  "london",
  "maidenhead",
  "manchester",
  "nottingham",
  "oxford",
  "reading",
  "rye",
  "sheffield",
  "southampton",
  "york",
  // London areas (multi-word — single-word areas caught by Mapbox fallback)
  "bethnal green",
  "brick lane",
  "camden town",
  "canary wharf",
  "covent garden",
  "king's cross",
  "kings cross",
  "london bridge",
  "notting hill",
  // US
  "atlanta",
  "austin",
  "boston",
  "chicago",
  "cleveland",
  "dallas",
  "denver",
  "detroit",
  "houston",
  "las vegas",
  "lasvegas",
  "los angeles",
  "losangeles",
  "miami",
  "milwaukee",
  "minneapolis",
  "new york",
  "newyork",
  "orlando",
  "philadelphia",
  "phoenix",
  "pittsburgh",
  "portland",
  "sacramento",
  "san antonio",
  "san diego",
  "san francisco",
  "sanfrancisco",
  "seattle",
  "tampa",
  // Spain
  "valencia",
];
