// Mapping from FilterPanel keys to DB columns
// TODO the allowed filters can be read from the database schema via a query to information_schema.columns
export const FILTER_KEY_TO_DB_COLUMN: Record<string, string> = {
  airConditioning: "air_conditioning",
  babyChangeMens: "baby_change_mens",
  babyChangeUnisex: "baby_change_unisex",
  babyChangeWomens: "baby_change_womens",
  buzzy: "buzzy",
  // changingTable: "changing_table",
  dogFriendly: "dog_friendly",
  freeKidsMeal: "free_kids_meal",
  friendlyStaff: "friendly_staff",
  funQuirky: "fun_quirky",
  gamesAvailable: "games_available",
  glutenFree: "gluten_free_options",
  glutenFreeOptions: "gluten_free_options",
  goodForGroups: "good_for_groups",
  halal: "halal",
  healthyOptions: "healthy_options",
  highChairs: "high_chairs",
  kidsColoring: "kids_coloring",
  kidsMenu: "kids_menu",
  kidsPlaySpace: "kids_play_space",
  kidsPottyToilet: "kids_potty_toilet",
  kosher: "kosher",
  onePoundKidsMeal: "one_pound_kids_meal",
  outdoorSeating: "outdoor_seating",
  playgroundNearby: "playground_nearby",
  posh: "posh",
  pramStorage: "pram_storage",
  quickService: "quick_service",
  relaxed: "relaxed",
  smallPlates: "small_plates",
  takeaway: "takeaway",
  teenFavourite: "teen_favourite",
  touristAttractionNearby: "tourist_attraction_nearby",
  veganOptions: "vegan_options",
  vegetarianOptions: "vegetarian_options",
  wheelchairAccess: "wheelchair_access",
};

export const AMENITY_DB_COLUMNS: readonly string[] = Array.from(
  new Set(Object.values(FILTER_KEY_TO_DB_COLUMN)),
);

export const ALL_CUISINE_TYPES = [
  "American",
  "Asian",
  "Bakery",
  "Bar & Grill",
  "BBQ",
  "Breakfast",
  "British",
  "Cafe",
  "Chinese",
  "Dessert",
  "European",
  "Filipino",
  "French",
  "Greek",
  "Indian",
  "International",
  "Italian",
  "Japanese",
  "Korean",
  "Kosher",
  "Latin American",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Persian",
  "Peruvian",
  "Portuguese",
  "Pub",
  "Sandwiches",
  "Seafood",
  "Spanish",
  "Steakhouse",
  "Thai",
  "Turkish",
  "Vegetarian",
];
