export const AMENITY_DB_COLUMNS = [
  'high_chairs',
  'baby_change_unisex',
  'kids_potty_toilet',
  'kids_coloring',
  'kids_play_space',
  'playground_nearby',
  'kids_menu',
  'free_kids_meal',
  'pram_storage',
  'games_available',
  'outdoor_seating',
  'wheelchair_access',
  'dog_friendly',
  'quick_service',
  'baby_change_womens',
  'baby_change_mens',
  'air_conditioning',
  'vegetarian_options',
  'vegan_options',
  'gluten_free_options',
  'small_plates',
  'healthy_options',
  'halal',
  'kosher',
  'fun_quirky',
  'relaxed',
  'buzzy',
  'posh',
  'good_for_groups',
  'teen_favourite',
  'friendly_staff',
  'takeaway',
  'one_pound_kids_meal',
  'tourist_attraction_nearby',
] as const;

export type AmenityDbColumn = (typeof AMENITY_DB_COLUMNS)[number];

// Mapping from FilterPanel keys to DB columns
export const FILTER_KEY_TO_DB_COLUMN: Record<string, AmenityDbColumn> = {
  kidsMenu: 'kids_menu',
  highChairs: 'high_chairs',
  changingTable: 'changing_table',
  wheelchairAccess: 'wheelchair_access',
  babyChangeWomens: 'baby_change_womens',
  babyChangeUnisex: 'baby_change_unisex',
  babyChangeMens: 'baby_change_mens',
  kidsPottyToilet: 'kids_potty_toilet',
  pramStorage: 'pram_storage',
  outdoorSeating: 'outdoor_seating',
  playgroundNearby: 'playground_nearby',
  airConditioning: 'air_conditioning',
  dogFriendly: 'dog_friendly',
  vegetarianOptions: 'vegetarian_options',
  veganOptions: 'vegan_options',
  glutenFreeOptions: 'gluten_free_options',
  smallPlates: 'small_plates',
  healthyOptions: 'healthy_options',
  halal: 'halal',
  kosher: 'kosher',
  funQuirky: 'fun_quirky',
  relaxed: 'relaxed',
  buzzy: 'buzzy',
  posh: 'posh',
  goodForGroups: 'good_for_groups',
  kidsColoring: 'kids_coloring',
  gamesAvailable: 'games_available',
  kidsPlaySpace: 'kids_play_space',
  teenFavourite: 'teen_favourite',
  quickService: 'quick_service',
  friendlyStaff: 'friendly_staff',
  takeaway: 'takeaway',
  freeKidsMeal: 'free_kids_meal',
  onePoundKidsMeal: 'one_pound_kids_meal',
  touristAttractionNearby: 'tourist_attraction_nearby',
};

// Simple phrase → amenity column mapping for search text like "kids coloring"
export const AMENITY_PHRASES_TO_DB_COLUMN: Record<string, AmenityDbColumn> = {
  'kids coloring': 'kids_coloring',
  'kids colouring': 'kids_coloring',
  'kids menu': 'kids_menu',
  'high chairs': 'high_chairs',
  'baby change womens': 'baby_change_womens',
  'baby change unisex': 'baby_change_unisex',
  'baby change mens': 'baby_change_mens',
  'kids potty toilet': 'kids_potty_toilet',
  'kids play space': 'kids_play_space',
  'playground nearby': 'playground_nearby',
  'free kids meal': 'free_kids_meal',
  'one pound kids meal': 'one_pound_kids_meal',
};

