/*
  # Import Batch 1: Restaurants 1 to 50
  
  Importing 50 restaurants from Nugget - StoreRocket Locations 3.csv
*/

INSERT INTO restaurants (name, slug, cuisine, address, latitude, longitude, phone, description, image_url, visible, family_friendly, high_chairs, baby_change_womens, baby_change_mens, baby_change_unisex, kids_menu, wheelchair_access, outdoor_seating, playground_nearby, small_plates, vegetarian_options, vegan_options, gluten_free_options, halal, kosher, fun_quirky, relaxed, buzzy, posh, good_for_groups, takeaway, dog_friendly, friendly_staff, healthy_options, quick_service, air_conditioning, kids_coloring, games_available, kids_play_space, kids_potty_toilet, teen_favourite, free_kids_meal, one_pound_kids_meal, tourist_attraction_nearby, pram_storage) VALUES
('Solar Sisters - Zero Waste - Refill - Café', 'solar-sister-cafe', 'Various', '86 North St, Guildford GU1 4AU, UK', 51.2367316, -0.5708077, NULL, 'A plant-based menu for breakfast, lunch, and afternoon tea. You can also grab a quick coffee or use the refill shop to stock up on the essentials. They also host events.', 'https://cdn.prod.website-files.com/65c4e3041d72984c18dbb740/670f8f4cb127b9b6e35c92e1_Color%2520logo%2520with%2520background%25201%2520(2).png', NULL, true, true, NULL, NULL, true, true, true, NULL, NULL, true, true, true, NULL, NULL, NULL, true, true, NULL, NULL, true, true, true, true, true, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Brags and Brams', 'brags-and-brams-london-england', 'Various', '265 Hackney Road', 51.5311982, -0.0685801, NULL, 'Super family-friendly brunch/lunch spot with fun kids'' meal options. Combine with Haggerston Park, Hackney City Farm, or the Young V&A Museum. You can also grab a coffee and pastry from the counter to-go.', 'https://cdn.prod.website-files.com/65c4e3041d72984c18dbb740/66e40bc62047f2460f93c27e_2%2BA07I8846%2Bweb.jpeg', true, true, true, true, NULL, NULL, true, true, NULL, true, NULL, true, true, true, NULL, NULL, NULL, true, true, NULL, true, true, true, true, true, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;